const { escapeValue, sanitizeColumnName } = require('../utils/sqlUtils');

/**
 * Generate INSERT statements from data
 */
const generateInsert = async (req, res, next) => {
  try {
    const { tableName, headers, rows, schema } = req.body;

    if (!tableName || !headers || !rows) {
      return res.status(400).json({ 
        error: true, 
        message: 'tableName, headers, and rows are required' 
      });
    }

    const sanitizedHeaders = headers.map(h => sanitizeColumnName(h));
    const columnsStr = sanitizedHeaders.join(', ');
    
    const insertStatements = rows.map(row => {
      const values = row.map((value, index) => {
        const type = schema ? schema[headers[index]] : 'VARCHAR';
        return escapeValue(value, type);
      });
      return `INSERT INTO ${sanitizeColumnName(tableName)} (${columnsStr}) VALUES (${values.join(', ')});`;
    });

    res.json({
      success: true,
      sql: insertStatements.join('\n'),
      statements: insertStatements,
      totalStatements: insertStatements.length
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Generate CREATE TABLE statement
 */
const generateCreateTable = async (req, res, next) => {
  try {
    const { tableName, schema } = req.body;

    if (!tableName || !schema) {
      return res.status(400).json({ 
        error: true, 
        message: 'tableName and schema are required' 
      });
    }

    const columns = Object.entries(schema).map(([name, type]) => {
      return `  ${sanitizeColumnName(name)} ${type.toUpperCase()}`;
    });

    const sql = `CREATE TABLE ${sanitizeColumnName(tableName)} (\n${columns.join(',\n')}\n);`;

    res.json({
      success: true,
      sql: sql
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Generate full SQL script (CREATE TABLE + INSERT statements)
 */
const generateFullScript = async (req, res, next) => {
  try {
    const { tableName, headers, rows, schema } = req.body;

    if (!tableName || !headers || !rows || !schema) {
      return res.status(400).json({ 
        error: true, 
        message: 'tableName, headers, rows, and schema are required' 
      });
    }

    // Generate CREATE TABLE
    const columns = Object.entries(schema).map(([name, type]) => {
      return `  ${sanitizeColumnName(name)} ${type.toUpperCase()}`;
    });
    const createTableSql = `CREATE TABLE ${sanitizeColumnName(tableName)} (\n${columns.join(',\n')}\n);`;

    // Generate INSERT statements
    const sanitizedHeaders = headers.map(h => sanitizeColumnName(h));
    const columnsStr = sanitizedHeaders.join(', ');
    
    const insertStatements = rows.map(row => {
      const values = row.map((value, index) => {
        const type = schema[headers[index]] || 'VARCHAR';
        return escapeValue(value, type);
      });
      return `INSERT INTO ${sanitizeColumnName(tableName)} (${columnsStr}) VALUES (${values.join(', ')});`;
    });

    const fullScript = `-- Generated by Data Extractor Tool\n-- Table: ${tableName}\n-- Generated at: ${new Date().toISOString()}\n\n${createTableSql}\n\n${insertStatements.join('\n')}`;

    res.json({
      success: true,
      sql: fullScript,
      createTable: createTableSql,
      insertStatements: insertStatements,
      totalRows: rows.length
    });
  } catch (error) {
    next(error);
  }
};

module.exports = {
  generateInsert,
  generateCreateTable,
  generateFullScript
};
